name: Build

on: [pull_request, push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board: ['espressif_kaluga_1', 'espressif_saola_1_wroom', 'espressif_saola_1_wrover', 'microdev_micro_s2', 'unexpectedmaker_feathers2']
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1

    - name: Pull ESP-IDF docker
      run: docker pull espressif/idf:latest

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Build
      run: docker run --rm -v $PWD:/project -w /project espressif/idf:latest idf.py build -DBOARD=${{ matrix.board }}

    - name: List files
      run: ls -a
